sudo: required

services:
- docker

before_script:
    # 登录到 docker hub
- docker login -u "$DOCKER_USERNAME" "$DOCKER_PASSWORD"

after_success:
  # 当代码测试通过后执行的命令
- docker build -t superservice/product-service-py .
- docker push superservice/product-service-py
